/**
 * HTML fixtures for deck export tests.
 *
 * These replicate the HTML structure generated by Hooks::buildDeckHtml().
 */

function basicDeckHtml() {
	return `
<div class="ext-scryfall-deck"><div class="ext-scryfall-decktitlecontainer">
<span class="ext-scryfall-decktitle">Burn Deck</span>
<div class="ext-scryfall-deckexport">
<button type="button" class="ext-scryfall-deckexport-dropbtn">Download/Export</button>
<ul class="ext-scryfall-deckexport-dropmenu">
<li><button title="Download in text format." type="button" class="ext-scryfall-deckexport-text">Text</button></li>
<li><button title="Download in Magic: The Gathering Online format." type="button" class="ext-scryfall-deckexport-mtgo">MTGO</button></li>
<li><button title="Download in Apprentice format." type="button" class="ext-scryfall-deckexport-apprentice">Apprentice</button></li>
<li><button title="Download in OCTGN format." type="button" class="ext-scryfall-deckexport-octgn">OCTGN</button></li>
<li><button title="Export to decklist.org." type="button" class="ext-scryfall-deckexport-decklist">decklist.org</button></li>
</ul>
</div></div><div class="ext-scryfall-deckcontents">
<div class="ext-scryfall-decksection">
<h4><span class="ext-scryfall-decksectiontitle">Instants</span> (8)</h4>
<p class="ext-scryfall-deckentry"><span class="ext-scryfall-deckcardcount">4</span> <a href="https://scryfall.com/search?q=test" class="ext-scryfall-cardname" data-card-name="Lightning Bolt">Lightning Bolt</a></p>
<p class="ext-scryfall-deckentry"><span class="ext-scryfall-deckcardcount">4</span> <a href="https://scryfall.com/search?q=test" class="ext-scryfall-cardname" data-card-name="Chain Lightning">Chain Lightning</a></p>
</div>
</div></div>`;
}

function deckWithSideboardHtml() {
	return `
<div class="ext-scryfall-deck"><div class="ext-scryfall-decktitlecontainer">
<span class="ext-scryfall-decktitle">Burn Deck</span>
<div class="ext-scryfall-deckexport">
<button type="button" class="ext-scryfall-deckexport-dropbtn">Download/Export</button>
<ul class="ext-scryfall-deckexport-dropmenu">
<li><button type="button" class="ext-scryfall-deckexport-text">Text</button></li>
<li><button type="button" class="ext-scryfall-deckexport-mtgo">MTGO</button></li>
<li><button type="button" class="ext-scryfall-deckexport-apprentice">Apprentice</button></li>
<li><button type="button" class="ext-scryfall-deckexport-octgn">OCTGN</button></li>
<li><button type="button" class="ext-scryfall-deckexport-decklist">decklist.org</button></li>
</ul>
</div></div><div class="ext-scryfall-deckcontents">
<div class="ext-scryfall-decksection">
<h4><span class="ext-scryfall-decksectiontitle">Instants</span> (4)</h4>
<p class="ext-scryfall-deckentry"><span class="ext-scryfall-deckcardcount">4</span> <a href="https://scryfall.com/search?q=test" class="ext-scryfall-cardname" data-card-name="Lightning Bolt">Lightning Bolt</a></p>
</div>
<div class="ext-scryfall-decksection ext-scryfall-decksideboard">
<h4><span class="ext-scryfall-decksectiontitle">Sideboard</span> (2)</h4>
<p class="ext-scryfall-deckentry"><span class="ext-scryfall-deckcardcount">2</span> <a href="https://scryfall.com/search?q=test" class="ext-scryfall-cardname" data-card-name="Pyroblast">Pyroblast</a></p>
</div>
</div></div>`;
}

module.exports = { basicDeckHtml, deckWithSideboardHtml };
